# Generated by Django 4.2.8 on 2024-04-10 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonVi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ten', models.CharField(max_length=100)),
                ('DiaChi', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NhanSu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HoDem', models.CharField(blank=True, max_length=50, null=True)),
                ('Ten', models.CharField(max_length=50)),
                ('NgaySinh', models.DateField()),
                ('HeSoLuong', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='NhanSuDonVi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VaiTro', models.CharField(choices=[('Nhân viên', 'Nhân viên'), ('Quản lý', 'Quản lý')], default='Nhân viên', max_length=20)),
                ('DangCongTac', models.BooleanField(default=True)),
                ('don_vi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlnhansu.donvi')),
                ('nhan_su', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlnhansu.nhansu')),
            ],
        ),
        migrations.AddField(
            model_name='nhansu',
            name='DonViLV',
            field=models.ManyToManyField(through='qlnhansu.NhanSuDonVi', to='qlnhansu.donvi'),
        ),
    ]
