# Generated by Django 4.2.8 on 2024-04-14 07:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonVi',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Ten', models.CharField(max_length=100)),
                ('DiaChi', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NhanSu',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('HoDem', models.CharField(max_length=50, null=True)),
                ('Ten', models.CharField(max_length=50)),
                ('NgaySinh', models.DateTimeField()),
                ('HeSoLuong', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)])),
            ],
        ),
        migrations.CreateModel(
            name='NhanSuDonVi',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('VaiTro', models.CharField(default='Nhân viên', max_length=20)),
                ('DangCongTac', models.BooleanField(default=True)),
                ('DonVi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlnhansu.donvi')),
                ('NhanSu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlnhansu.nhansu')),
            ],
        ),
        migrations.AddField(
            model_name='nhansu',
            name='DonViLV',
            field=models.ManyToManyField(through='qlnhansu.NhanSuDonVi', to='qlnhansu.donvi'),
        ),
    ]
